version: "3"
services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
        - postgres
    command: postgres:5432
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    restart: always
  selenium:
    image: selenium/standalone-chrome-debug:3.2.0-actinium
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build: ./app
    container_name: app-server
    hostname: app-server
    depends_on:
      - postgres
      - waitfordb
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@moodle_postgres_1:5432/moodle
      SELENIUM_URL: http://selenium:4444/wd/hub
      TZ: "Asia/Tokyo"
    tty: true
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 8888:8888
    restart: always
  web:
    container_name: web-server
    hostname: web-server
    build: ./web
    volumes:
        - "./web/nginx.conf:/etc/nginx/nginx.conf"
        # nginxのログをホストOS側に出力
        - "/tmp/nginx_log:/var/log/nginx"
    depends_on:
      - app
    links:
      - app
    ports:
      - "80:80"
    environment:
      TZ: Asia/Tokyo
    restart: always

    
