version: "3"
services:
  waitfordb:
    container_name: wait-for-db
    hostname: wait-for-db
    image: dadarek/wait-for-dependencies
    depends_on:
        - postgres
    command: postgres:5432
  postgres:
    container_name: db-server
    hostname: db-server
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    restart: always
  selenium:
    container_name: selenium-server
    hostname: selenium-server
    image: selenium/standalone-chrome-debug:3.2.0-actinium
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    container_name: app-server
    hostname: app-server
    depends_on:
      - postgres
      - waitfordb
    volumes:
      - "./src:/var/www/src"
      - "/dev/shm:/dev/shm"
      # loggerのログをホストOS側に出力
      - "/tmp/uvicorn/log:/var/log/uvicorn"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-server:5432/moodle
      SELENIUM_URL: http://selenium-server:4444/wd/hub
      # moodle account for scraping
      MOODLE_ID: $MOODLE_ID
      MOODLE_PASSWORD: $MOODLE_PASSWORD
      # gmail account for smtp 
      GMAIL_ACCOUNT: $GMAIL_ACCOUNT
      GMAIL_PASSWORD: $GMAIL_PASSWORD
      # jwt settings
      SECRET_KEY: $SECRET_KEY
      SECRET_N: $SECRET_N
      SECRET_E: $SECRET_E
      SECRET_KTY: $SECRET_KTY
      
      # time zone
      TZ: "Asia/Tokyo"
    tty: true
    ports:
      - 10000:10000
    restart: always
  web:
    container_name: web-server
    hostname: web-server
    build: 
        context: ./
        dockerfile: docker/web/Dockerfile
    volumes:
        - type: bind
          source: "./docker/web/nginx.conf"
          target: "/etc/nginx/nginx.conf"
        # nginxのログをホストOS側に出力
        - "/tmp/nginx_log:/var/log/nginx"
    depends_on:
      - app
    links:
      - app
    ports:
      - "80:80"
      - "${PORT:-8443:443}"
    environment:
      TZ: Asia/Tokyo
    restart: always
  frontend:
    image: node:16
    ports:
      - "3000:3000"
    volumes:
      - ./front:/var/www/front
    working_dir: /var/www/front
    environment:
      ADMIN_ACCOUNT: $ADMIN_ACCOUNT
      ADMIN_PASSWORD: $ADMIN_PASSWORD
    command: /bin/sh -c "yarn && yarn generate-client && yarn start"
