version: "3"
services:
  waitfordb:
    container_name: wait-for-db
    hostname: wait-for-db
    image: dadarek/wait-for-dependencies
    depends_on:
        - postgres
    command: postgres:5432
  postgres:
    container_name: db-server
    hostname: db-server
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    restart: always
  selenium:
    container_name: selenium-server
    hostname: selenium-server
    image: selenium/standalone-chrome-debug:3.2.0-actinium
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    container_name: app-server
    hostname: app-server
    depends_on:
      - postgres
      - waitfordb
    volumes:
      - "./src:/var/www/src"
      - "/dev/shm:/dev/shm"
      # loggerのログをホストOS側に出力
      - "/tmp/uvicorn\log:/var/log/uvicorn"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-server:5432/moodle
      SELENIUM_URL: http://selenium:4444/wd/hub
      # moodleの認証情報
      MOODLE_ID: ""
      MOODLE_PASSWORD: ""
      # smtpの認証情報
      GMAIL_ACCOUNT: ""
      GMAIL_PASSWORD: ""
      TZ: "Asia/Tokyo"
    tty: true
    ports:
      - 8888:8888
    restart: always
  web:
    container_name: web-server
    hostname: web-server
    build: 
        context: ./
        dockerfile: docker/web/Dockerfile
    volumes:
        # nginxのログをホストOS側に出力
        - "/tmp/nginx_log:/var/log/nginx"
    depends_on:
      - app
    links:
      - app
    ports:
      - "80:80"
      - "${PORT:-8443:443}"
    environment:
      TZ: Asia/Tokyo
    restart: always
