version: "3"
services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
        - postgres
    command: postgres:5432
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    restart: always
  selenium:
    image: selenium/standalone-chrome-debug:3.2.0-actinium
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build: ./docker/app
    container_name: app-server
    hostname: app-server
    depends_on:
      - postgres
      - waitfordb
    volumes:
      - "./src:/src"
      - "/dev/shm:/dev/shm"
      # loggerのログをホストOS側に出力
      - "/tmp/application_log:./src/logs/application.log"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@moodle_postgres_1:5432/moodle
      SELENIUM_URL: http://selenium:4444/wd/hub
      # moodleの認証情報
      MOODLE_ID: "change me"
      MOODLE_PASSWORD: "change me"
      # smtpの認証情報
      GMAIL_ACCOUNT: "change me"
      GMAIL_PASSWORD: "change me"
      TZ: "Asia/Tokyo"
    tty: true
    ports:
      - 8888:8888
    restart: always
  web:
    container_name: web-server
    hostname: web-server
    build: ./docker/web
    volumes:
        - "./web/nginx.conf:/etc/nginx/nginx.conf"
        - "./web/ssl:/etc/nginx/ssl"
        # nginxのログをホストOS側に出力
        - "/tmp/nginx_log:/var/log/nginx"
    depends_on:
      - app
    links:
      - app
    ports:
      #- "80:80"
      - "${PORT:-8443:443}"
    environment:
      TZ: Asia/Tokyo
    restart: always

    
